<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Aggregates\Customer\Entities\" />
    <Folder Include="Aggregates\Customer\Specifications\" />
    <Folder Include="SharedKernel\" />
    <Folder Include="SeedWork\Events\" />
    <Folder Include="SeedWork\Specification\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
	<PackageReference Include="MediatR.Contracts" Version="2.0.1" />
	  
  </ItemGroup>

</Project>
